project:
  type: website

website:
  navbar:
    logo: "Picture/Logo.png"
    background: success
    left:
      - text: "Hands-on Exerciese"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3(a)"
            href: "Hands-on_Ex/Hands-on_Ex03(a)/Hands-on_Ex03(a).html"
          - text: "Hands-on Exercise 3(b)"
            href: "Hands-on_Ex/Hands-on_Ex03(b)/Hands-on_Ex03(b).html"
          - text: "Hands-on Exercise 4(a)"
            href: "Hands-on_Ex/Hands-on_Ex04(a)/Hands-on_Ex04(a).html"
          - text: "Hands-on Exercise 4(b)"
            href: "Hands-on_Ex/Hands-on_Ex04(b)/Hands-on_Ex04(b).html"
          - text: "Hands-on Exercise 4(c)"
            href: "Hands-on_Ex/Hands-on_Ex04(c)/Hands-on_Ex04(c).html"
          - text: "Hands-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Hands-on Exercise 7"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
          - text: "Hands-on Exercise 8(a)"
            href: "Hands-on_Ex/Hands-on_Ex08(a)/Hands-on_Ex08(a).html"
          - text: "Hands-on Exercise 8(b)"
            href: "Hands-on_Ex/Hands-on_Ex08(b)/Hands-on_Ex08(b).html"
          - text: "Hands-on Exercise 8(c)"
            href: "Hands-on_Ex/Hands-on_Ex08(c)/Hands-on_Ex08(c).html"
          - text: "Hands-on Exercise 9(a)"
            href: "Hands-on_Ex/Hands-on_Ex09(a)/Hands-on_Ex09(a).html"
          - text: "Hands-on Exercise 9(b)"
            href: "Hands-on_Ex/Hands-on_Ex09(b)/Hands-on_Ex09(b).html"
          - text: "Hands-on Exercise 9(c)"
            href: "Hands-on_Ex/Hands-on_Ex09(c)/Hands-on_Ex09(c).html"
          - text: "Hands-on Exercise 9(d)"
            href: "Hands-on_Ex/Hands-on_Ex09(d)/Hands-on_Ex09(d).html"
          - text: "Hands-on Exercise 10"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
      - text: "In-class Exercise"  
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
          - text: "In-class Exercise 4"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "In-class Exercise 5"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
          - text: "In-class Exercise 6"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
          - text: "In-class Exercise 7"
            href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
          - text: "In-class Exercise 8"
            href: "In-class_Ex/In-class_Ex08/In-class_Ex08.html"
          - text: "In-class Exercise 9"
            href: "In-class_Ex/In-class_Ex09/In-class_Ex09.html"
          - text: "In-class Exercise 10"
            href: "In-class_Ex/In-class_Ex10/In-class_Ex10.html"
      - text: "Take-home Exercise"  
        menu: 
          - text: "Take-home Exercise 1"
            href: "Take-Home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 2"
            href: "Take-Home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take-home Exercise 3"
            href: "Take-Home_Ex/Take-home_Ex03/Take-home_Ex03.html"
      - text: "Group Project"  
        href: "https://oceanus-fish.netlify.app"

    right:
      - about.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Fnrion/jiaxun.zou
          - text: Report a Bug
            href:  https://bugs.com
format:
  html:
    theme:
      light: Journal
      dark: cosmo
    toc: true
    fontsize: 1 em
    linestretch: 1.6
    backgroundcolor: Ivory
    light: flatly
    dark: darkly
editor: visual